### ISSUE TITLE
配置.env后，输入指令中的任意字母都会触发

### ISSUE THREAD

**Issue by WeiLanKing** [Harry-Jing/nonebot-plugin-bing-chat#12]
bingchat_command_chat = "bchat"
如果信息中包含这5个字母，都会触发指令

**Comment by Harry-Jing** [comment]
请问你的配置文件的字符串是否使用单引号

**Comment by small-bili** [comment]
我也遇到了这个问题，并没有使用单引号，也没有使用中文符号，通过将字符串变量改为列表就好
