### ISSUE TITLE
提问部分内容调用content_simple时出错

### ISSUE THREAD

**Issue by shizhiye** [Harry-Jing/nonebot-plugin-bing-chat#13]
提问 chat サガプラネッツ的全部作品有哪些？
qq返回 <调用content_simple时出错>
<无效的响应值, 请管理员查看控制台>

03-05 01:57:57 [INFO] nonebot_plugin_gocqhttp | [2858352056] 发送群 test(706053038) 的消息: [{"type":  ... (-1299447791)03-05 01:58:17 [ERROR] nonebot_plugin_bing_chat | {'type': 2, 'invocationId': '0', 'item': {'messages': [{'text': 'サガ プラネッツ的全部作品有哪些？', 'topicChangerText': 'Suggest a topic.', 'author': 'user', 'from': {'id': '844428454516157', 'name': None}, 'createdAt': '2023-03-04T17:57:57.9526446+00:00', 'timestamp': '2023-03-04T17:57:57.950243+00:00', 'locale': 'en-us', 'market': 'en-us', 'region': 'us', 'messageId': 'e71baac4-bb5b-4bf6-98ba-8d9eb58b1810', 'requestId': 'e71baac4-bb5b-4bf6-98ba-8d9eb58b1810', 'offense': 'OffenseTrigger', 'feedback': {'tag': None, 'updatedOn': None, 'type': 'None'}, 'contentOrigin': 'cib', 'privacy': None, 'inputMethod': 'Keyboard'}, {'hiddenText': "Sorry, I don't have enough knowledge to talk about this.  By the way, were you aware pteronophobia is the fear of being tickled by feathers", 'topicChangerText': 'By the way, were you aware pteronophobia is the fear of being tickled by feathers', 'author': 'bot', 'createdAt': '2023-03-04T17:58:05.1121673+00:00', 'timestamp': '2023-03-04T17:58:05.1121673+00:00', 'messageId': '95f63bed-880f-437c-9471-524b379e6145', 'requestId': 'e71baac4-bb5b-4bf6-98ba-8d9eb58b1810', 'offense': 'None', 'adaptiveCards': [{'type': 'AdaptiveCard', 'body': [{'type': 'TextBlock', 'text': "Sorry, I don't have enough knowledge to talk about this. You can learn more on [bing.com](https://bing.com?q=%e3%82%b5%e3%82%ac%e3%83%97%e3%83%a9%e3%83%8d%e3%83%83%e3%83%84%e7%9a%84%e5%85%a8%e9%83%a8%e4%bd%9c%e5%93%81%e6%9c%89%e5%93%aa%e4%ba%9b%ef%bc%9f). ", 'wrap': True}, {'type': 'TextBlock', 'text': 'By the way, were you aware pteronophobia is the fear of being tickled by feathers', 'wrap': True}]}], 'sourceAttributions': [{'providerDisplayName': 'SAGA PLANETS - 維基百科，自由的百科全書', 'seeMoreUrl': 'https://zh.wikipedia.org/zh-tw/SAGA_PLANETS', 'searchQuery': 'サガプラネッツ 作品'}, {'providerDisplayName': 'SAGA PLANETSとは (サガプラネッツ とは) [単語記事] - ニコニコ大百科', 'seeMoreUrl': 'https://dic.nicovideo.jp/a/saga%20planets', 'searchQuery': 'サガプラ ネッツ 作品'}, {'providerDisplayName': 'SAGA PLANETS OFFICIAL HOMEPAGE', 'seeMoreUrl': 'http://sagapla.net/top.html', 'searchQuery': 'サガプラネッツ 作品'}, {'providerDisplayName': 'SAGA PLANETS OFFICIAL HOMEPAGE', 'seeMoreUrl': 'https://sagapla.net/', 'searchQuery': 'サガプラネッツ 作品'}], 'feedback': {'tag': None, 'updatedOn': None, 'type': 'None'}, 'contentOrigin': 'Apology', 'scores': [{'component': 'content_filter', 'score': 1}], 'privacy': None}], 'firstNewMessageIndex': 1, 'conversationId': '51D|BingProd|3F03158FBA96F0FE1CAFD0D5004EA5E02F54EF59DA8960AEC4D55AD0576037EF', 'requestId': 'e71baac4-bb5b-4bf6-98ba-8d9eb58b1810', 'conversationExpiryTime': '2023-03-04T23:58:16.9318456Z', 'shouldInitiateConversation': False, 'telemetry': {'metrics': None, 'startTime': '2023-03-04T17:57:57.9503092Z'}, 'throttling': {'maxNumUserMessagesInConversation': 6, 'numUserMessagesInConversation': 1}, 'result': {'value': 'Success', 'message': 'サガプラネッツ  作品', 'serviceVersion': '20230304.13'}}}

**Comment by Harry-Jing** [comment]
不是文字类的Adaptive Card，暂时不支持

**Comment by Harry-Jing** [comment]
![image](https://user-images.githubusercontent.com/69247286/222951021-06e782c6-6c34-4fa1-9de9-55aa7ee26136.png)

**Comment by shizhiye** [comment]
好的 明白了

**Comment by Harry-Jing** [comment]
我会加这部分的处理的

**Comment by Harry-Jing** [comment]
fix in v0.4.0
