### ISSUE TITLE
[🚀 Feature] 更加自然的连续对话与群内共享对话

### ISSUE THREAD

**Issue by Nova-Noir** [Harry-Jing/nonebot-plugin-bing-chat#20]
目前版本请求 bing 时必须输入命令，在连续对话时显得较为繁琐。

## How
- [ ] 添加配置项以支持在 `@bot 聊天内容` 时自动请求 Bing，设置为 True 时覆写 `BING_COMMAND_CHAT`
- [ ] 添加配置项以修改上述功能的优先级，方便用户自定义来调整触发频率（例如，用户还有其它 `@bot 聊天内容` 的应用，想要将 BING 相应放在最后，此时可以调整优先级的配置到其它应用后，并设置其他应用的 `block=1`）

具体实现可以参考 [chatgpt](https://github.com/A-kirami/nonebot-plugin-chatgpt) 利用钩子函数在启动成功读取配置项后再添加即可。

**Comment by Harry-Jing** [comment]
在 #11 中有另一种实现思路

**Comment by Nova-Noir** [comment]
> 在 #11 中有另一种实现思路

这个也是不错的思路。我可以提供另一种想法，可能会更加适用一点？每次开启 chat 后记录 msg_id 和 chat_id，通过回复 bot 的回复即可继续聊天，并且甚至可以添加配置项以支持多人共享同一对话。

实例是这样的：
| 聊天人 | msg id | chat_id | 聊天内容 |
| --- | --- | --- | --- |
| A | 0 | 0 | `chat 请告诉我 XXX` |
| bot | 1 | 0 | `[REPLY msgid=0] XXX 是什么样的` |
| A | 2 | 0 | `[REPLY msgid=1] 那 YYY 呢` |
| bot | 3 | 0 | `[REPLY msgid=2 YYY 是这样的` |
| B | 4 |0 | `[REPLY msgid=3 请告诉 YYY 更详细的信息` |
| bot | 5 | 0 | `[REPLY msgid=4 好的，YYY 是这样的` |

**Comment by Harry-Jing** [comment]
确实，直接回复消息来继续进行对话是一个很好的的实现方式

**Comment by Harry-Jing** [comment]
我感觉实现起来好复杂，要重构好多地方

**Comment by Nova-Noir** [comment]
是这样的，基本上得大改了

**Comment by Harry-Jing** [comment]
部分在v0.5.0中实现
