### ISSUE TITLE
[🚀 Feature] 可以返回带有参考链接的内容

### ISSUE THREAD

**Issue by coyude** [Harry-Jing/nonebot-plugin-bing-chat#22]
网页版必应的回复下方都是下方带有参考链接的，所以大佬可以在插件回复用户的时候把下方参考链接也加上吗？
![123](https://user-images.githubusercontent.com/24607145/223300560-7c996ce6-ac61-4f7a-8a50-bba53b7e4474.png)

**Comment by Harry-Jing** [comment]
与 #16 有关

**Comment by Harry-Jing** [comment]
在 0.6.0-alpha.1 中实现，需要修改配置文件

**Comment by coyude** [comment]
> 

感谢大佬！

**Comment by Harry-Jing** [comment]
在 0.6.0-alpha.3 中提高可读性

**Comment by Harry-Jing** [comment]
在0.7.0a1中有更好的实现
