### ISSUE TITLE
一处小小的错误

### ISSUE THREAD

**Issue by citydirector** [Harry-Jing/nonebot-plugin-bing-chat#24]
nonebot_plugin_bing_chat/common/utils.py
第51行，历史记录应为plugin_config.bingchat_command_history_chat
![image](https://user-images.githubusercontent.com/45933075/224417184-6f1d50c5-df0f-4f83-8550-6649da92d7a4.png)

**Comment by Harry-Jing** [comment]
在 0.5.1 中修复
