### ISSUE TITLE
[🐛 Bug] v0.5.1所有指令都会被 nonebot-plugin-bing-chat 阻断，导致其他插件指令无法触发

### ISSUE THREAD

**Issue by ElaineOwO** [Harry-Jing/nonebot-plugin-bing-chat#25]
03-11 10:51:59 [SUCCESS] nonebot | OneBot V11  | [message.group.normal]: Message  from @[群:] "有点熟悉这个金毛"
03-11 10:51:59 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_bing_chat.common.utils)
03-11 10:51:59 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_bing_chat.common.utils) running complete
03-11 10:52:00 [SUCCESS] nonebot | OneBot V11  | [message.group.normal]: Message - from @[群:] "今日欲望"
03-11 10:52:00 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_bing_chat.common.utils)
03-11 10:52:00 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_bing_chat.common.utils) running complete

**Comment by ElaineOwO** [comment]
好像并不影响触发其他插件 是我沙壁了_(:з)∠)_

**Comment by citydirector** [comment]
确实是会影响，看日志里指令都指向了这个插件

**Comment by cj1357** [comment]
> 确实是会影响，看日志里指令都指向了这个插件

我也是，其它插件的前缀指令都不触发了，只有bing响应

**Comment by Harry-Jing** [comment]
所以为什么会被block

**Comment by cj1357** [comment]
> 所以为什么会被block

我回退到0cf24a42b21abad9d2bce2148186225c35a7bcce这个版本是不会block的，刚刚试了一下，不知道为什么

**Comment by cj1357** [comment]
> > 所以为什么会被block
> 
> 我回退到0cf24a42b21abad9d2bce2148186225c35a7bcce这个版本是不会block的，刚刚试了一下，不知道为什么

再次更新到5c9d2d9这个提交（0cf24a4的下一个提交），就不会响应其它插件的前缀指令了

**Comment by Harry-Jing** [comment]
在 0.5.2 中修复

**Comment by cj1357** [comment]
> 在 0.5.2 中修复

还是没有修复喔。
我刚才试了试把common/utils.py里面的message_all = on_message()注释掉之后，就不会阻塞其它插件的指令了，应该就是这段代码造成的（我注释掉了插件还是可以用 嘿嘿）

**Comment by Harry-Jing** [comment]
才发现默认on_message的block=True

**Comment by Harry-Jing** [comment]
在 0.5.3 中修正

**Comment by Harry-Jing** [comment]
我属于是犯傻了0.5.3没有将本地的push上来就发布了。。
