### ISSUE TITLE
[🚀 Feature] 添加配置项，允许回复消息时不显示“正在请求”

### ISSUE THREAD

**Issue by xxtg666** [Harry-Jing/nonebot-plugin-bing-chat#27]
感觉这个“正在请求”的提示有时候比较难看，最好可以设置是否显示这个提示。

**Comment by Harry-Jing** [comment]
在 0.5.2 中实现

**Comment by cj1357** [comment]
> 在 0.5.2 中实现

你好像忘记写到readme里面了，这个配置字段bingchat_show_is_waiting
