### ISSUE TITLE
chat指令出问题

### ISSUE THREAD

**Issue by ability66** [Harry-Jing/nonebot-plugin-bing-chat#29]
<无法创建Chatbot>
Exceeded 30 redirects.
![image](https://user-images.githubusercontent.com/106503132/224651087-95e602b4-69d3-4661-99ee-9f1350ba7198.png)

**Comment by Harry-Jing** [comment]
临时在 v0.6.0-alpha.2 中修复

**Comment by Harry-Jing** [comment]
在 v0.6.0-alpha.4 中修复
