### ISSUE TITLE
你好 有个问题想询问一下 

### ISSUE THREAD

**Issue by 1592735160** [Harry-Jing/nonebot-plugin-bing-chat#3]
这个newbing插件是需要获得newbing的测试资格才可以使用这个newbing插件吗 抱歉这个问题有点无脑的样子  因为我在引用后返回给我的错误信息是
<无法创建Chatbot>
Authentication failed. You have not been accepted into the beta.
我不太确定是我的操作流程有问题还是因为我没有获得newbing的测试资格

**Comment by Harry-Jing** [comment]
是需要访问新Bing的资格，确保你已经拥有了New Bing的访问资格
