### ISSUE TITLE
一个对话只能回复一次

### ISSUE THREAD

**Issue by wurenand** [Harry-Jing/nonebot-plugin-bing-chat#35]
![image](https://user-images.githubusercontent.com/109780598/225783457-3a6fbf78-900f-4e5c-8f22-e6384a25e3e7.png)

**Comment by wurenand** [comment]
问第二次就会出现这个问题，只能chat-new刷新

**Comment by Yiyoki** [comment]
重复 #33

**Comment by cj1357** [comment]
我也遇到了，刚更新的

**Comment by cj1357** [comment]
> 我也遇到了，刚更新的

![image](https://user-images.githubusercontent.com/40661342/225859718-0e025e21-b074-4369-8727-7c1bbd41298f.png)

**Comment by Harry-Jing** [comment]
与 #33 重复
