### ISSUE TITLE
您好~我发现有两个问题~

### ISSUE THREAD

**Issue by hechushitaoyuan** [Harry-Jing/nonebot-plugin-bing-chat#4]
第一个是用脚手架安装后，找不到插件，无法加载，看了下是安装后在虚拟环境的site-packages里面没有nonebot_plugin_bing_chat文件夹，通过下载文件把里面的这个文件夹复制进来后才能正常加载插件。
第二个是测试后报错：.venv\Lib\site-packages\nonebot_plugin_bing_chat\__init__.py", line 35, in bing_chat_command_chat is_valid_user, return_str = permissionsCheck(event=event)
TypeError: cannot unpack non-iterable NoneType object
我在查了下是说：
permissionsCheck函数是在这个文件中定义的：nonebot_plugin_bing_chat/utils.py。根据这个文件，permissionsCheck函数有可能返回None，如果event没有user_id或者user_id不在白名单中会遇到TypeError: cannot unpack non-iterable NoneType object的错误，因为试图从一个None值中解包两个变量。我尝试在config的白名单里添加QQ号，可是依然没有成功。

**Comment by Harry-Jing** [comment]
对于第二个问题这个我不是很确定，我测试的时候是没有问题的

**Comment by Harry-Jing** [comment]
ob11正常来说是会返回一个有效的event类型

**Comment by hechushitaoyuan** [comment]
> 请发送完整的报错文件

您稍等~吃完饭我发您邮箱~~麻烦了~~

**Comment by Harry-Jing** [comment]
你使用得应该不是最新的插件，请尝试使用脚手架/pip从新安装，并确保你是在虚拟环境中运行

**Comment by YouYouLip** [comment]
> 经过我的测试是我的`pyproject.toml`在更改时误写成了scr-layout，导致build的时候找不到包裹

我也是 site-packages里面有nonebot_plugin_bing_chat-0.2.0.dist-info但是没有nonebot_plugin_bing_chat主体

**Comment by Harry-Jing** [comment]
在 v0.2.1修复

**Comment by Harry-Jing** [comment]
尝试使用 `nb plugin install nonebot-plugin-bing-chat --upgrade` 更新

**Comment by YouYouLip** [comment]
> 尝试使用 `nb plugin install nonebot-plugin-bing-chat --upgrade` 更新

解决啦解决啦 虚拟环境内有插件主体了

**Comment by Harry-Jing** [comment]
我看文档的时候走眼了，没把库包含到里面 awq
