### ISSUE TITLE
bot<无法创建Chatbot> Authentication failed

### ISSUE THREAD

**Issue by Ayase-Naka-a** [Harry-Jing/nonebot-plugin-bing-chat#42]
[nonebot-plugin-bing-chat]和[EdgeGPT]已经更新到最新
![image](https://user-images.githubusercontent.com/117055433/227086285-bf2e0cd3-513f-4bc1-bedc-0b4edd585803.png)
![image](https://user-images.githubusercontent.com/117055433/227089213-9a69c38d-db18-40c3-88cc-cb4153db29fc.png)
提示认证失败，实际使用账号登录www.bing.com，可以在网页上直接与bing对话

bot报错提示，gocq使用的是手表协议
![A0@IXP_B `~0EZ07DYE0TRM](https://user-images.githubusercontent.com/117055433/227089340-e96af6da-ba6e-470d-a581-fb56640828b8.png)

昨天还能正常使用，期间未对bot进行任何修改，今天突然报错不知道是什么原因引起的

**Comment by Harry-Jing** [comment]
请尝试更新cookies

**Comment by Harry-Jing** [comment]
Bing已更新，不能再使用国内ip进行访问

**Comment by Ayase-Naka-a** [comment]
清楚了，后续插件是否会增加使用代理访问功能

**Comment by Harry-Jing** [comment]
会的
