### ISSUE TITLE
Authentication failed. You have not been accepted into the beta.

### ISSUE THREAD

**Issue by AlexZhou1995** [Harry-Jing/nonebot-plugin-bing-chat#43]
已经用了大半个月了，中间也出现过这个错误，我通过重新产出cookie来解决的。
今天又出现了这个问题，重新产出了cookie也没用，还是这个错误 : (

服务器不在国内，排除国内IP问题。

**Comment by VMTask** [comment]
你被微软从候补名单踢出去了

**Comment by cj1357** [comment]
python3 -m pip install EdgeGPT --upgrade
已经修复了
