### ISSUE TITLE
关于请求并发的问题。

### ISSUE THREAD

**Issue by linkedlist771** [Harry-Jing/nonebot-plugin-bing-chat#5]
进过测试，您制作的new bing chat bot好像是单线程请求的，而且同一个人在不同群进行请求时还会发生错乱。

**Comment by Harry-Jing** [comment]
每个人的请求理论上是可以同时进行的

**Comment by Harry-Jing** [comment]
在一个人发送请求后，在得到响应前不应该再次尝试发送请求，将会添加此限制

**Comment by Harry-Jing** [comment]
在 v0.3.0 中修复
