### ISSUE TITLE
能否增加自动刷新对话的功能

### ISSUE THREAD

**Issue by pk4ever1** [Harry-Jing/nonebot-plugin-bing-chat#6]
目前只能连续对话五次？
超过了还得艾特机器人刷新对话。挺麻烦的。
能否加个新功能。在超过了这个上限后自动进行刷新操作重新开始新的对话。

超过上限后AI会回复如下内容。
【Thanks for this conversation! I've reached my limit, will you hit “New topic,” please?】
【That's the most I can say about that. Click “New topic” and we can keep chatting!】
【Sorry, I think we need to move on! Click “New topic” to chat about something else.】

提两个案：
1.也许能根据是否含有【“New topic”】来判断是否超过上限
2.通过count对话次数自行判断。如果这个次数能配置的话以后bing更新了上限也能继续留用

🙏

**Comment by Harry-Jing** [comment]
在 v0.3.3中增加了检查是否超过上限的功能

**Comment by Harry-Jing** [comment]
在 v0.3.4 中实现
