### ISSUE TITLE
No message is sent if bingchat_display_is_waiting is set

### ISSUE THREAD

**Issue by mcwindy** [Harry-Jing/nonebot-plugin-bing-chat#60]
No message is sent if "bingchat_display_is_waiting=False" or "bingchat_display_is_waiting=True" is set in the environment file.

➜ ~  pip list | findstr bing
nonebot-plugin-bing-chat   0.7.8

**Comment by Harry-Jing** [comment]
貌似没有问题

**Comment by mcwindy** [comment]
Quite strange. I can not reproduce the problem. Anyway, thanks for ur help.
