### ISSUE TITLE
蓝bing脑袋不是很好使

### ISSUE THREAD

**Issue by WeCanLandHere** [Harry-Jing/nonebot-plugin-bing-chat#71]
我一般都用创造力紫bing，有办法把默认的蓝bing切换成紫bing吗

**Comment by WeCanLandHere** [comment]
![5(_)%SB2B5K~1WQ4Z4HVQEY](https://github.com/Harry-Jing/nonebot-plugin-bing-chat/assets/81317833/e542e68f-848d-40e1-8006-44b3185b76a0)
![IG7M2`B2OBIPZM1W(6LZ2OB](https://github.com/Harry-Jing/nonebot-plugin-bing-chat/assets/81317833/db82b39c-360c-48e7-a1e0-9c746aad6a02)

**Comment by cj1357** [comment]
![image](https://github.com/Harry-Jing/nonebot-plugin-bing-chat/assets/40661342/a3bec252-d2c1-4bab-8793-53a0a928bd09)
可以改配置选择填写"creative"就是创造力紫色模式了
