### ISSUE TITLE
无法通过脚手架下载

### ISSUE THREAD

**Issue by Moekey114514** [Harry-Jing/nonebot-plugin-bing-chat#8]
![image](https://user-images.githubusercontent.com/48763754/221467400-f673fdcb-f835-455c-8fe1-2bce25c450b1.png)
如图，报错提示Could not find a version that satisfies the requirement nonebot-plugin-bing-chat (from versions: none)，可能是版本号没配上？

**Comment by Harry-Jing** [comment]
不支持python3.9，需要python3.10+

**Comment by Moekey114514** [comment]
原来如比，感谢解答

**Comment by Ikaros-521** [comment]
我这针对python3.8的兼容做了魔改，可以参考
[https://github.com/Ikaros-521/nonebot-plugin-bing-chat](https://github.com/Ikaros-521/nonebot-plugin-bing-chat)

**Comment by Harry-Jing** [comment]
我记得好像就两个match-case的语句，改一下应该就可以了

**Comment by Ikaros-521** [comment]
> 我记得好像就两个match-case的语句，改一下应该就可以了

3.8改了不少，3.9可能部分语法兼容0.0

**Comment by Harry-Jing** [comment]
哦对，3.9才可以这样写类型注释

**Comment by Ikaros-521** [comment]
![(U}6}N~MZ5@LPK) I42TO D](https://user-images.githubusercontent.com/40910637/222322128-333ac1c6-9114-4b5d-b5f0-ec5a12384e39.jpg)
是时候考虑升级py了

**Comment by Harry-Jing** [comment]
类型注释真好用（

**Comment by Ikaros-521** [comment]
centos7表示很痛苦（当时就应该直接重装了）
![SS }AO9L~ZOV2F`77_TBN(I](https://user-images.githubusercontent.com/40910637/222322488-5e2e2b40-614f-46a2-9467-faac94170407.gif)

**Comment by Harry-Jing** [comment]
可以升级的吧

**Comment by Ikaros-521** [comment]
可以，但我不想在编译一遍了，痛苦
